apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
  creationTimestamp: 2020-04-13T05:08:55Z
  generation: 7
  labels:
    app: node-proxy
  name: node-proxy
  namespace: mfp
  resourceVersion: "779209"
  selfLink: /apis/extensions/v1beta1/namespaces/mfp/deployments/node-proxy
  uid: dff78637-7d44-11ea-a30d-82f271a4fab6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: node-proxy
      version: 1.0.0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-proxy
        version: 1.0.0
    spec:
      containers:
      - env:
        - name: TARGET
          value: https://10.100.200.2:8443
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        image: docker-registry.default.svc:5000/mfp/node-proxy:1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /lbcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: node-proxy
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /lbcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 8
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          requests:
            cpu: "1"
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-04-13T06:52:20Z
    lastUpdateTime: 2020-04-13T06:52:20Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2020-04-13T05:08:55Z
    lastUpdateTime: 2020-04-13T06:54:33Z
    message: ReplicaSet "node-proxy-5f77df5fbc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
